name: gen
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

#runtime
dependencies:
  flutter:
    sdk: flutter

  # Config
  envied: ^1.1.1

  # Network
  dio_nexus: ^0.3.3

  # Core
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  # IU
  flutter_svg: ^2.0.17
  lottie: ^3.3.1


# build
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  very_good_analysis: ^7.0.0
  build_runner: ^2.4.15
  envied_generator: ^1.1.1
  json_serializable: ^6.9.4
  flutter_gen_runner: ^5.10.0

flutter_gen:
  output: lib/src/asset/
  integrations:
    flutter_svg: true
    lottie: true

  colors:
    inputs:
      - assets/color/colors.xml

flutter:
  assets:
    - assets/color/
    - assets/icons/
    - assets/images/
    - assets/lottie/