name: flutter_valorant_agents
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.4
  stacked_services: ^1.1.0

  # Config
  easy_localization: ^3.0.7+1

  # Network
  dio_nexus: ^0.3.3
  dio: ^5.8.0+1

  # UI
  flutter_screenutil: ^5.9.3

  gen:
    path: module/gen
  common:
    path: module/common

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.6.1
  golden_toolkit: ^0.15.0

dependency_overrides:
  logger: ^2.5.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

