name: common
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # Network
  cached_network_image: ^3.4.1

  # Core
  path_provider: ^2.1.5
  keyboard_dismisser: ^3.0.0
  
  # Toast
  fluttertoast: ^8.2.12

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0